## Basic configuration
retraining: False
training: True # If the model is train, this argument should be true, else False
dataset: 'C:\\Users\\18917\\PycharmProjects\\Virtual word is coming\\VOCdevkit-262'
imageset: 2007_test
tfrecord_file: 'data/tf-record'
tfrecord_num: 20000
samples_per_file: 1000

## The size, the iter number to run...
batch_size: 1 # Batch size of the data
num_epochs: 1 # Number of the train epochs
learning_rate: 1.0e-3 # Learning rate for the optimizer

## Save configure
log_path: log # Path to save the log
model_path: model # Path to save the model
save_epoch: 2000 # The frequency to save the model
save_summary: 10 # The frequency to save the summary
